### ISSUE TITLE
fetch on/off state of a bulb

### ISSUE THREAD

**Issue by FordAndii** [Foddy/node-red-contrib-huemagic#95] opened 2019-08-29 21:12 UTC
Hi, I want to determine the state of a bulb (on/off).

The documentation says about the hue.bridge node:

> Use the Fetch command to retrieve various information from the Hue Bridge when needed. Pass the fetch property to msg.payload.

However, I don't get this to work. Whatever value I send as an inut to the hue-bridge node ("fetch", "lights", "fetch=lights", ...), the output of the hue-bridge node is always the same. It's just an object listing several properties of the bridge, but no information about the connected bulbs.

I would be grateful if you could show an example showing how to use the hue-bridge node to fetch these properties.

Thank you!

**Comment by lucwuyts** [comment] 2019-08-30 02:28
If you send a json object like this:  { "fetch": "lights" }  it answers with the status of every light

**Comment by ozett** [comment] 2019-12-01 17:53
the docu is somehow misleading. i had the same problem as "Ford Andii" https://github.com/Foddy/node-red-contrib-huemagic/issues/95#issue-487178411

i would think that some simple sample-flows for import could help to clear things up

**Comment by fendle** [comment] 2020-02-26 21:51
I tried the following JSON {"fetch":"users"} and get an undefined object in the debug.

**Comment by NicApicella** [comment] 2020-04-25 01:38
Have the same issue as @fendle on 2.6.2 (on Nodered 1.0.3). Injecting a timestamp returns the bridge data immediately; injecting the JSON-object { "fetch": "lights" } returns "undefined" while the label on the bridge states "fetching lights…" for about a second or two.
I'm guessing it's a bug: The output gets triggered before the bridge has had the time to actually fetch the information.

Managed to grab a screenshot at just the right moment. First debug output was after injecting a timestamp; second was right after the light-fetch statement. Notice the label on the bridge.
<img width="992" alt="huemagicfetch" src="https://user-images.githubusercontent.com/10376774/80268269-0ed8be00-86a6-11ea-85be-0c9ef3577119.png">

**Comment by discofris** [comment] 2020-05-13 09:34
I have the exact same [issue](https://github.com/Foddy/node-red-contrib-huemagic/issues/95#issuecomment-619299716) on Node-RED 1.0.6 with Hue Magic 2.7.0

**Comment by PedanticPete** [comment] 2020-05-15 10:53
Hi I'm on a pi

I've started everything again from scratch ...

Node v12.16.3   Npm 6.14.5

I can connect to the Bridge, get a new API user, I can rename the hub, I can turn a light on, but can I get fetch to work ... no, completely stuck, the fetch users example in the bridge example

"payload": "{\"fetch\":\"users\"}",
"payloadType": "json", 

just doesn't work - HELP - I can work the bridge fine from the CLIP API with the GET command ...

Pete

**Comment by Swiiney** [comment] 2020-08-11 12:25
Hi, I have the same problem on my Pi.

I can't fetch the status, it returns "undefined".
I get the same with the global update events. I receive the event but it says "undefined".

Stephane
Pi 4 with node-red-contrib-huemagic 2.8.2 on Nodered latest docker image

**Comment by Slomo17** [comment] 2020-10-04 11:41
Same problem here with Node-red 1.1.1 and huemagic 2.8.6.
I am searching for a way to safe the current state of all lights, to restore them later.

**Comment by arnoks** [comment] 2020-10-08 14:34
I had the same issue using nodered 1.1.3 and huematic 2.8.6. However the problem vanished when I switched on the two lights which were registered but not reachable by the hue bridge. Those lights are usually manually switched off completely and consequently their status is unknown to the bridge. However, once it was working I was not able to reproduce the error. Seems to be some corner case in the inital setup procedure of the bridge.

**Comment by iverona** [comment] 2020-10-14 16:25
Same here. Worked once I switched on all the unreachable lights. But it took two attempts to fetch lights information. First one did just return the typical bridge info.

**Comment by coxifred** [comment] 2020-11-03 22:21
> Have the same issue as @fendle on 2.6.2 (on Nodered 1.0.3). Injecting a timestamp returns the bridge data immediately; injecting the JSON-object { "fetch": "lights" } returns "undefined" while the label on the bridge states "fetching lights…" for about a second or two.
> I'm guessing it's a bug: The output gets triggered before the bridge has had the time to actually fetch the information.
> 
> Managed to grab a screenshot at just the right moment. First debug output was after injecting a timestamp; second was right after the light-fetch statement. Notice the label on the bridge.
> <img alt="huemagicfetch" width="992" src="https://user-images.githubusercontent.com/10376774/80268269-0ed8be00-86a6-11ea-85be-0c9ef3577119.png">

You have to (in your debug node) change to msg.lights, instead of msg.payload

**Comment by coxifred** [comment] 2020-11-03 22:23
The best ways would be to make able the Hue Light Node to receive fetch query !

**Comment by pihlo99** [comment] 2021-02-26 16:28
Same as described - looks that this is still an open issue...?

**Comment by BruthaVoodoo** [comment] 2021-08-10 18:43
So has there been a resolution to this? Im seeing the same issue...

**Comment by Foddy** [comment] 2022-01-09 20:22
Should be fixed in the latest version. Please send the following command to get the current state of a light bulb `{ "payload": { "status": true }}` or the { "payload": { "fetch": "light }} command on a "Hue Bridge" node

**Closed by Foddy** 2022-01-09 20:22 UTC
