### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mondface** [Foddy/node-red-contrib-huemagic#106] opened 2019-10-21 09:02 UTC
hi,
i get these errors since 2.0.4:

node:841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which wa
node-red.0	2019-10-21 10:59:46.542	warn	(node:841) UnhandledPromiseRejectionWarning: Error: Huejay: connect ENETUNREACH 192.168.178.82:80 at getHttpClient.request.then.catch.error (/opt/iobroker/iobroker-data/node-red/node_modules/hueja

Gruß frAnk

**Comment by Foddy** [comment] 2019-10-22 05:53
Hi Frank! Do you use NodeJS 10.x or higher?

**Comment by mondface** [comment] 2019-10-22 13:18
Moin Foddy,
it is NodeJS '8.16.2'
Gruß frAnk

**Comment by Foddy** [comment] 2019-10-23 07:58
Hi frAnk,

I‘m pretty sure that this causes the error. Please upgrade to NodeJS 10+ if this is not conflicting with any other modules and try again.

Grüße zurück ;)

**Comment by mondface** [comment] 2019-10-23 14:44
hi foddy,
ich have upgrade, but i got the same error!
node -v
v10.17.0
npm -v
6.11.3
Gruß frAnk

**Comment by mondface** [comment] 2019-10-23 14:46
i have no 192.168.178.82:80  in my network!

**Comment by ozett** [comment] 2019-11-04 09:03
======

4 Nov 10:02:13 - [info] Node-RED Version: v1.0.2
4 Nov 10:02:13 - [info] Node.js  Version: v11.5.0
4 Nov 10:02:13 - [info] Linux 3.14-1-amd64 x64 LE
4 Nov 10:02:13 - [info] Paletten-Nodes werden geladen
4 Nov 10:02:13 - [debug] Module: node-red-contrib-bigtimer 2.2.5

======
root@deb8mpd-virt:~/.node-red# npm -v
6.12.0


```
node:17401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 289)
(node:17401) UnhandledPromiseRejectionWarning: Error: Huejay: Request failed with status code 404
    at getHttpClient.request.then.catch.error (/root/.node-red/node_modules/huejay/lib/Transport.js:106:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:17401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 291)
(node:17401) UnhandledPromiseRejectionWarning: Error: Huejay: Request failed with status code 404
    at getHttpClient.request.then.catch.error (/root/.node-red/node_modules/huejay/lib/Transport.js:106:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:17401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 293)
4 Nov 10:01:13 - [debug] [hue-bridge:Hue Bridge] Error: Huejay: Request failed with status code 404
    at getHttpClient.request.then.catch.error (/root/.node-red/node_modules/huejay/lib/Transport.js:106:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:17401) UnhandledPromiseRejectionWarning: Error: Huejay: Request failed with status code 404
    at getHttpClient.request.then.catch.error (/root/.node-red/node_modules/huejay/lib/Transport.js:106:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:17401) Unhandled
```

any help welcome

**Comment by ozett** [comment] 2019-11-04 09:08
i uninstalled huemagic und now have this error

```
4 Nov 10:05:51 - [info] Warten auf fehlende Typen, die registriert werden sollen:
4 Nov 10:05:51 - [info]  - hue-bridge
```
what to do now?

**Comment by Lastat77** [comment] 2020-01-13 03:23
node -v: v10.18.0
npm -v : 6.13.4
Node-Red: 1.0.3

I have the following errors every couple of 10 minutes or so:

`(node:15765) UnhandledPromiseRejectionWarning: Error: Huejay: connect ENETUNREACH 10.0.10.162:80 - Local (0.0.0.0:0) at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15) at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)`

I have attached pictures of the flows and ui produced.

This is all on a Raspberry 4. I also have a Raspberry Zero W - same issues - however, the Zero seems to have a much harder time recovering form the error (becomes unresponsive for long (5 to 7 minutes) periods of time. The Pi 4 doesn't seem interrupted; just produces the error.

![ScreenCap 2020-01-12 at 9 16 10 PM](https://user-images.githubusercontent.com/27899259/72231557-c1669400-3581-11ea-88e2-b7ecf64df76c.png)
![ScreenCap 2020-01-12 at 9 16 16 PM](https://user-images.githubusercontent.com/27899259/72231558-c1669400-3581-11ea-9490-7c3b85fc840f.png)
![ScreenCap 2020-01-12 at 9 17 29 PM](https://user-images.githubusercontent.com/27899259/72231559-c1669400-3581-11ea-823d-055a386813ba.png)
![ScreenCap 2020-01-12 at 9 17 53 PM](https://user-images.githubusercontent.com/27899259/72231560-c1ff2a80-3581-11ea-91f3-cd5dd9c29e5a.png)

**Comment by ozett** [comment] 2020-01-13 07:40
@Lastat77 
i cannot help with the problem, but i find the flow interesing.
Would you mind sharing it here (as an export from node-red) ?

greatly  appreciated, and thx,
toz

**Comment by Lastat77** [comment] 2020-01-14 08:28
@ozett

Hopefully the error can be addressed at some point.

Attached are `.json` of the flows. I have removed the HUE's key/user id code and the HUE Bridge name. Also, the GPIO's are disabled in case your PIN usage is different and present.

[flows.zip](https://github.com/Foddy/node-red-contrib-huemagic/files/4058086/flows.zip)

**Comment by GHBLoos** [comment] 2020-02-03 22:16
I have the same problem.

```
(node:17022) UnhandledPromiseRejectionWarning: Error: Huejay: Request failed with status code 404
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 479)
```
It has been working, but not anymore. I hope someone can throw some light on this issue.

**Comment by Lastat77** [comment] 2020-02-03 22:35
Yeah, still here... If I use flows that include this set of nodes, the PI becomes basically frozen after just a bit of use (couple minutes/10/20 clicks). Sometimes I can ssh to it and reboot, but often it has to be hard bounced.

I have re-imaged, switched power cords, switched sd cards; tried everything. Only thing that works is to not use this node - which isn't really an option since this node, when working, is really great. I even tried using dietpi over rasbian - no different (if not worse).

So now I have a cron job to reboot the pi every hour. Not ideal (and ironically, as I type this, I am unable to get to the pi again).

**Comment by GHBLoos** [comment] 2020-02-04 11:43
My Pi doesn't freeze. I just can't find the diyHue bridge when creating the flow. My Philips Hue bridge is visible and I can use that in the flow.
The strange thing is that it has worked (diyHue with Node Red).

I will setup a new Pi and see if it works there. 

It would already help if we can find out if the problem is in the HueMagic node or in the diyHue (or even somewhere else).

**Comment by Lastat77** [comment] 2020-02-04 19:37
Seems from the error I read, the underlying issue is actually HueJay and the node not catching it "properly". (not a knowledgable expert here).

**Comment by Travelbacon** [comment] 2020-03-22 20:56
I have exact the same problem. It seems that it happens when there is a good hick up in the network where Node-RED is running. This will causes a stop of reading data back from the Hue Bridge. You can send commands to the Hue Bridge, but not read data back. 

**My test**
I tested it by making a small flow with a light and two injections. One with {"On":true} and one with {"On":false} to turn the bulf on or off. When I noticed that the Hue Magic nodes were hanging, I checked if this simple flow was able to turn to bulb on and off. The real bulb was going on and off, but the status of the bulb remained off in Node-RED. When you deploy new nodes that contains a Hue Magic Node the problem is gone. Every node gives back the status of the devices/scenes etc.. Same by deploy all or restart the node red service. Deploy with modified nodes does not fix this issue.

**My configuration**
My problem is caused on Hue Magic on Rpi3 with a very low CPU load. But I know that my Pi has sometimes some network issues. 

**Analysis**
I think that this might be the issue together that the Node-RED reports about a catch issue in the code.
```

Mar 22 08:32:42 framframmetje Node-RED[7812]: (node:7812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Mar 22 08:32:42 framframmetje Node-RED[7812]: (node:7812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
I took a small peek in the code of Hue Magic to see if I can find the root cause, but was unable to get in to the code. Perhaps you, as programmer, know directly where the problem should be.

I checked the syslog etc. if there were other things going on. I've analyzed several hangs and couldn't find any correlations. I have detailed information of a hang, because I send the temperature of a Hue sensor to the cloud. When Hue Magic hangs, no data is received.

**Comment by Travelbacon** [comment] 2020-03-23 17:32
More information. My Hue nodes were hangin on one flow only.
Flow light control had old data instead of status waiting... But my new flow with only the bulb and two injections were working fine. The real bulb's status was read in the node in this test flow.
In the syslog I see that the error of UnhandledPromises came up several times today

**Comment by GeorgeCastanza** [comment] 2020-07-12 02:33
I'm getting this as well.  I have been for some time. It's causing significant errors. 

NodeJS 12.18.2 
NodeRed 1.1.1
NPM 6.14.5
Latest HueMagic nodes. 

I also get the unhandled error on startup too.

**Comment by Lastat77** [comment] 2020-07-13 11:52
I have also updated everything to latest versions. Issue still present. But the auto-reboot (cron) I employed makes it all OK in a sense. In my use case, a reboot every hour is fine - and probably a bit overkill. Could probably just reboot nightly.

**Comment by Travelbacon** [comment] 2020-07-19 17:01
I noticed that it happens when my network has a heavy load. I think a time out is the root cause fo this.

**Comment by Travelbacon** [comment] 2020-08-30 09:37
I made some progress to find the root cause of this. It seems that in Huejay the handling of network feedback from the bridge need improvement.

I notice that this only occurs when my network has heavy load to handle or my Pi is busy.  When you've a Pi, the huejay responds slower that a fast Intel-based computer. That could explain why you will see this more or only on the Pies than a PC.

When I made a test to send a lot of data to the HueBridge I saw the feedback from the Bridge to slow down, but the flows ignore this. Then the Hue Bridge will disconnect the nodes for small time. A proper flow should stop sending when the receiver gives a signal to slow down. The same is that the nodes don't reset connection when a time out occurs.

**Comment by Travelbacon** [comment] 2020-08-30 09:41
https://github.com/sqmk/huejay/issues/115

**Comment by GeorgeCastanza** [comment] 2020-10-19 00:54
> I made some progress to find the root cause of this. It seems that in Huejay the handling of network feedback from the bridge need improvement.
> 
> I notice that this only occurs when my network has heavy load to handle or my Pi is busy. When you've a Pi, the huejay responds slower that a fast Intel-based computer. That could explain why you will see this more or only on the Pies than a PC.
> 
> When I made a test to send a lot of data to the HueBridge I saw the feedback from the Bridge to slow down, but the flows ignore this. Then the Hue Bridge will disconnect the nodes for small time. A proper flow should stop sending when the receiver gives a signal to slow down. The same is that the nodes don't reset connection when a time out occurs.

I hope this able to be resolved soon. I'm using a OdroidN2 to host Node Red, and it doesnt do anything else.  It should have enough power to handle these Hue commands.

**Comment by Brewj** [comment] 2021-03-08 21:56
+1 with the same issue :-(

`(node:5816) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded
    at /home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
(node:5816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 166)`

**Comment by Foddy** [comment] 2022-01-09 20:09
Fixed with the v4 update :)

**Closed by Foddy** 2022-01-09 20:09 UTC
Labels: bug
