### ISSUE TITLE
Unable to get the status of a lamp in universal mode 

### ISSUE THREAD

**Issue by papetebk** [Foddy/node-red-contrib-huemagic#156] opened 2020-04-10 23:38 UTC
**Describe the bug**
Sice the update to v2.6.2  I don't get a answer msg with lamp status, when I send a command to the lamp node in universal mode.

Before the update to v2.6.2, I sent a command to e.g. lamp 5 (Lamp node in universal mode) and I got a status information from lamp 5 on the output from lamp node.

**Flow to Reproduce**
```
`[{"id":"690e8418.6fa1d4","type":"debug","z":"3e8a3baf.b498ec","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1170,"y":540,"wires":[]},{"id":"7e2d74c0.9ce6a4","type":"hue-light","z":"3e8a3baf.b498ec","name":"","bridge":"1cda1aff.491725","lightid":"","colornamer":true,"skipevents":false,"x":1020,"y":540,"wires":[["690e8418.6fa1d4"]]},{"id":"17abdf1.a28b721","type":"function","z":"3e8a3baf.b498ec","name":"Inject lampnumber","func":"msg.payload = {\"brightness\":msg.payload};\nmsg.topic = \"32\";\nreturn msg;","outputs":1,"noerr":0,"x":810,"y":540,"wires":[["7e2d74c0.9ce6a4"]]},{"id":"aecd8e09.f560e8","type":"inject","z":"3e8a3baf.b498ec","name":"","topic":"","payload":"90","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":570,"y":460,"wires":[["17abdf1.a28b721"]]},{"id":"e46bf4f9.4286c","type":"inject","z":"3e8a3baf.b498ec","name":"","topic":"","payload":"50","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":570,"y":500,"wires":[["17abdf1.a28b721"]]},{"id":"cb093103.04b8d","type":"inject","z":"3e8a3baf.b498ec","name":"","topic":"","payload":"20","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":570,"y":540,"wires":[["17abdf1.a28b721"]]},{"id":"1cda1aff.491725","type":"hue-bridge","z":"","name":"Philips hue","bridge":"192.168.178.71","key":"Sl4IDYGDjVfZe5bAApaaWjMvK99LvzFLZd46gaDY","interval":"3000","disableupdates":false}]`
```

**Expected behavior**
Fix that problem in the next release.

**Please complete the following information:**
 - NodeRED version: v1.0.4
 - NodeJS version: v12.16.1
 - Device running NodeRED: Raps 3b+

**Comment by Foddy** [comment] 2020-04-26 16:07
Duplicate of #154 / fixed with v2.6.4

**Closed by Foddy** 2020-04-26 16:07 UTC
Labels: bug
