### ISSUE TITLE
Unable to set color by using hex

### ISSUE THREAD

**Issue by klein0r** [Foddy/node-red-contrib-huemagic#35] opened 2018-02-11 16:00 UTC
If I send the following payload to a light node, it always changes to a specific blue (004bff) instead of the provided color.

Example:

```
{ payload: { hex: "55fc65" } }
```

Change-event for the new color is always:

```
msg.payload {
  on: true
  brightness: 100
  rgb: [0, 75, 255]
  hex: "004bff"
  updated: "2018-02-11T15:57:47+00:00"
}
```

What is going on here? Using NodeRed 0.17.5 and node v6.11.3

**Comment by Foddy** [comment] 2018-02-17 09:37
Duplicate of #30

**Closed by Foddy** 2018-02-17 09:37 UTC

**Comment by klein0r** [comment] 2018-02-17 12:33
I don't think it's a duplicate of #30 - I am not able to change the color of the Hue bulbs to anything. It will ALWAYS result in blue (004bff). Changing it in the app or the api directly is working fine. There must be an issue in the hex conversion.

**Comment by Foddy** [comment] 2018-02-17 17:51
I have used the same payload with the same hex value and can not reproduce the error. Can you try this flow with the latest version of HueMagic?

`[{"id":"788bf116.22eaf","type":"inject","z":"98ee540.5ceec3","name":"","topic":"","payload":"{\"hex\":\"55fc65\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":"","x":340,"y":180,"wires":[["a14298db.f50c08"]]},{"id":"a14298db.f50c08","type":"hue-light","z":"98ee540.5ceec3","name":"Filmlicht","bridge":"94d83a9d.7d7c9","lightid":"7","x":540,"y":180,"wires":[["1c8f713.fefca0f"]]},{"id":"94d83a9d.7d7c9","type":"hue-bridge","z":"","name":"Foddy Hue Bridge","bridge":"192.168.0.100","key":"F42iT5PO5NtrlZ56AkD8RnmQhsor-4c77n18-0PJ","interval":"5000"}]`

**Comment by amlarsendk** [comment] 2018-03-04 16:51
I have the exact same issue - no matter what hex value I specify I get the same color: 004bff.
Using NodeRed 0.17.5, HueMagic 1.4.1

**Comment by sensorius** [comment] 2018-03-05 05:56
Just for confirmation, I do have the same odd "004bff" behaviour as klein0r.

**Comment by maikischa** [comment] 2018-03-08 13:07
I also can confirm this issue. I have 
node v6.11.4
node-red v0.18.4
node-red-contrib-huemagic 1.4.1
HUE Bridge BSB002 | 1801260942 
HUE bloom LLC011 | 5.105.1.21778

Have this problem for a while now

**Comment by Head** [comment] 2018-03-13 17:42
Same here
