### ISSUE TITLE
Lights are not turned off / on is working 2.8.0 (extended mode)

### ISSUE THREAD

**Issue by unclej84** [Foddy/node-red-contrib-huemagic#179] opened 2020-06-21 13:40 UTC
**Describe the bug**
After updating from 2.7.2 to 2.8.0 the lights can be switched on but aren't switched of when sending {on: "false} (extended mode). The node-red status changes to "off" in the node status but nothing happens. When sending boolean false the light is switched off (simple mode).

**Expected behavior**
When switching off the light should be turned off regardless of mode used.

**Please complete the following information:**
 - Node-RED version: [1.0.5]
 - NodeJS version: [v10.20.0]
 - Device running Node-RED: [Raspberry Pi 4B+ 4GB with RaspberryMatic and RedMatic]

**Additional context**
Maybe current RedMatic version is just not suitable for 2.8.0

**Comment by Foddy** [comment] 2020-06-22 07:32
Can you please try that again with this example? I tried to replicate your issue but for me it works as expected with 2.8.0?

`[{"id":"dfe4b558.db7be","type":"tab","label":"Issue #179","disabled":false,"info":""},{"id":"8da2e546.81d3a8","type":"hue-light","z":"dfe4b558.db7be","name":"","lightid":"","colornamer":true,"skipevents":false,"x":380,"y":100,"wires":[[]]},{"id":"570e482e.a953d","type":"inject","z":"dfe4b558.db7be","name":"","topic":"","payload":"{\"on\":false}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":60,"wires":[["8da2e546.81d3a8"]]},{"id":"e2608d13.1a25e","type":"inject","z":"dfe4b558.db7be","name":"","topic":"","payload":"{\"on\":true}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":140,"wires":[["8da2e546.81d3a8"]]}]`

**Comment by unclej84** [comment] 2020-06-22 09:52
Good morning,

thanks for your quick replay. I have tried and that seems to work - strange enough because I tried the same with a change node and an inject yesterday and could have be it did not work.
I noticed that the difference between your test and my real flow is a transition time in the off flow and that does not work. Please find the modified example attached (hope I copied correctly)

`[{"id":"f1ece58.ddeee18","type":"tab","label":"Issue #179","disabled":false,"info":""},{"id":"b1f6331d.a5ff2","type":"hue-light","z":"f1ece58.ddeee18","name":"","lightid":"","colornamer":true,"skipevents":false,"x":400,"y":100,"wires":[[]]},{"id":"ed8f9ca6.e0edc","type":"inject","z":"f1ece58.ddeee18","name":"","topic":"","payload":"{\"on\":false,\"transitionTime\":5}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":60,"wires":[["b1f6331d.a5ff2"]]},{"id":"c04a9938.a5e668","type":"inject","z":"f1ece58.ddeee18","name":"","topic":"","payload":"{\"on\":true}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":140,"wires":[["b1f6331d.a5ff2"]]}]`

**Comment by unclej84** [comment] 2020-06-22 09:55
Still the same result with 2.8.1 (in case this helps)

**Comment by Raul-7-7** [comment] 2020-06-25 05:01
Hi, I am having exact same issue, can not turn off with transition. if you remove the transition works fine :( is there anyway to go back to the previous version?

**Comment by unclej84** [comment] 2020-06-25 05:05
Hi Raul, yes, you can uninstall the new version and install old version using console `npm install node-red-contrib-huemagic@<version>`. If using RedMatic you have to load environment values first - see [here](https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-npm-auf-der-kommandozeile)

**Comment by Raul-7-7** [comment] 2020-06-25 05:14
Thanks for the quick reply @unclej84 , how do I Uninstall the current version? I cant remove it from the pallets as its in use in all my flows! :(

**Comment by unclej84** [comment] 2020-06-25 06:21
I used `npm uninstall node-red-contrib-huemagic` on the console to do it without touching Node-RED in between. I am not sure if you can uninstall via pallets when having in use.

**Comment by Raul-7-7** [comment] 2020-06-25 16:24
Thanks man, that worked !!! lesson learnt, if something is working perfect, don't touch it! lol :)

**Comment by sognen** [comment] 2020-06-29 23:49
Seeing the same. Version 2.7.2 works.

**Comment by dongennl** [comment] 2020-07-01 20:15
same for me. trying to downgrade; doesn't work with transitions.

**Comment by DotOnedotNL** [comment] 2020-07-09 07:21
It is not only transitionTime that is not working.
Any other value sent together with the "on": false message will prevent the lights from switching off.

I sent the "ignoreOffLights" and a "localContext" value as well
localContext is usually silently ignored.
the "on": false value is the only thing allowed in the message currently when switching off the lights.

**Comment by johras** [comment] 2020-07-09 17:14
> It is not only transitionTime that is not working.
> Any other value sent together with the "on": false message will prevent the lights from switching off.

Confirmed. Just faced the same problem with version 2.8.1

**Comment by Raul-7-7** [comment] 2020-07-09 17:23
Guys just **downgrade** to 2.7.2 , it works with no issue.

**Comment by unclej84** [comment] 2020-07-09 18:56
The issue seems to be related to the "// SAVE FOR LATER MODE?"-Section. For groups or lights it is checked if they are **not** on and only if the commands are processed. That is not working for switching off the lights in extended mode.

For lights (2.8.1) in line 458:
`if(!light.on||!light.reachable)`

and for group (2.8.1) in line 433:
`if(!group.on)`

I tried to remove "!light.on" and it was working as expected.

As far as I understood the code for simple ON / OFF the save function gets called directly but extended is passing thru this section, in which "payload.on" gets deleted.

`
				        // SAVE FOR LATER MODE?
					if(!group.on)
					{
						futureState = msg;

						// IGNORE ON/OFF & TOGGLE
						if(typeof futureState.payload != 'undefined')
						{
							delete futureState.payload.on;
							delete futureState.payload.toggle;
						}

						// ANY OTHER COMMANDS?
						if(typeof futureState.payload != 'undefined' && Object.keys(futureState.payload).length > 0)
						{
							return group;
						}
					}

					return bridge.client.groups.save(group);`

Can someone confirm this? Why is the code even checking if the light shall be on? Checking reachable should be enought, shouldn't it? But I am not sure about groups because there is no "reachable".

**Comment by Onixarts** [comment] 2020-07-11 15:19
I've also got this. Now all my home lights are turned on :D. After downgrade to 2.7.2 it works fine. This kind of bug should be repaired asap. It's one of the the main features.

**Comment by Foddy** [comment] 2020-07-12 10:58
Sorry! That was a pretty stupid logic error on my part.. I've tested it with the latest version (v2.8.2) and it seems to be fixed now. Maybe it makes sense to create a full featured example flow for every available node and action to rule out such errors in the future… :S

**Closed by Foddy** 2020-07-12 10:58 UTC
Labels: bug

**Comment by johras** [comment] 2020-07-13 06:34
All groups / lights node is still affected by this bug in version 2.8.2
In addition this node shows "some lights on" even when all are off or on.

**Comment by Onixarts** [comment] 2020-07-19 19:45
This cause wrong statuses in my home automation hub software, and I can't switch lights because the logic is based on current status.

**Comment by zeromancer1972** [comment] 2020-11-26 23:21
Issue still around with 3.0.0. I am sending

```
{
on: false
brightness: 34
hex: "36a6ff"
}
```

but the light always returns

```
{
on: true
brightness: 34
brightnessLevel: 86
reachable: true
rgb: array[3]
hex: "37adff"
colorTemp: 153
updated: "2020-11-26T23:18:52+00:00"
}
```

It is not possible to turn it on/off in extended mode.
