### ISSUE TITLE
Sometimes getting: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hpitumx** [Foddy/node-red-contrib-huemagic#230] opened 2021-04-12 07:22 UTC
**Describe the bug**
Unfortantly this bug is not easy to reproduce, but I do get it regulary. When I first start getting it, I get it repeatedly. 
In my logs I get 
12 Apr 08:46:24 - [error] [hue-group:Bedrom] RangeError: Maximum call stack size exceeded
And the flow stops working. 

**Flow to Reproduce**
```
[{"id":"a4176584.c02968","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b0b13234.2d488","type":"function","z":"a4176584.c02968","name":"","func":"console.log(msg);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":1200,"y":340,"wires":[[]]},{"id":"9c84d510.a88cd8","type":"hue-group","z":"a4176584.c02968","name":"Bedrom","bridge":"888b8b07.37ef78","groupid":"3","colornamer":true,"skipevents":false,"x":990,"y":340,"wires":[["b0b13234.2d488"]]},{"id":"3bcf5830.b98308","type":"function","z":"a4176584.c02968","name":"Hue OFF","func":"msg.payload = {on: false};\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":740,"y":340,"wires":[["9c84d510.a88cd8"]]},{"id":"edc3154.21034e8","type":"http in","z":"a4176584.c02968","name":"","url":"/offwhite","method":"get","upload":false,"swaggerDoc":"","x":490,"y":340,"wires":[["3bcf5830.b98308"]]},{"id":"888b8b07.37ef78","type":"hue-bridge","name":"Philips hue","bridge":"10.90.0.25","key":"xxx","interval":"3000","disableupdates":false}]
```

**Expected behavior**
No error in the log, and the flow works. 

**Screenshots**

**Please complete the following information:**
 - Node-RED version: 1.3.1
 - NodeJS version: 14.16.0
 - Device running Node-RED: Windows 10

**Additional context**
Redeployment of the flow or restarting node red both fix the problem.

**Comment by schweighart** [comment] 2021-04-30 22:34
I have the same issue but it only affects the Hue lightstrip for me. The Hue play always work.
I'm running Node-RED version 1.3.3 in Home Assistant on Debian.

Is there a way to get better log messages?

**Comment by dbowerman** [comment] 2021-06-01 03:13
I have the same issue. Nodered docker image on raspberry pi.

node-red_1  | 1 Jun 13:12:43 - [info] Node-RED version: v1.3.4
node-red_1  | 1 Jun 13:12:43 - [info] Node.js  version: v10.24.1
node-red_1  | 1 Jun 13:12:43 - [info] Linux 5.10.17-v7l+ arm LE

node-red-contrib-huemagic 3.0.0

**Comment by dbowerman** [comment] 2021-07-07 06:26
i have the same issue too. Nodered docker image on raspberry pi.

node-red_1  | 7 Jul 16:19:54 - [info] Node-RED version: v1.3.5
node-red_1  | 7 Jul 16:19:54 - [info] Node.js  version: v12.22.1
node-red_1  | 7 Jul 16:19:54 - [info] Linux 5.10.17-v7l+ arm LE

**Comment by NadeoWolf** [comment] 2021-11-14 11:11
Duplicate of #200

**Comment by NadeoWolf** [comment] 2021-11-14 11:14
The Problem is, that the Lamp sends a msg everytime there is an update. But for the HTTP Response, you need only messages for real requests, AND you need the res and req objects inside the message. Right now res and req will get Deleted from the hue Nodes and you need to bypass and merge the http and lamp messages if you want to return the new huw status.

**Closed** 2022-01-09 19:55 UTC
Labels: bug
